document.write("       <div id=\"navbar-main\">");
document.write("            <!-- Fixed navbar -->");
document.write("		<div class=\"navbar navbar-inverse navbar-fixed-top\">");
document.write("                <div class=\"container\">");
document.write("                    <div class=\"navbar-header\">");
document.write("                        <button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\" data-target=\".navbar-collapse\">");
document.write("                            <span class=\"icon icon-globe\" style=\"font-size:30px; color:#3498db;\"></span>");
document.write("                        </button>");
document.write("                        <!--<a class=\"navbar-brand hidden-xs hidden-sm\" href=\"#home\"><span style=\"font-size:18px; color:#3498db;\"></span></a>-->");
document.write("                    </div>");
document.write("                    <div class=\"navbar-collapse collapse\">");
document.write("                        <ul class=\"nav navbar-nav\">");
document.write("                            <li> <a href=\"http:\/\/noise-planet.org\/en\/index.html\" class=\"smoothScroll\"><i class=\"fa fa-home\" aria-hidden=\"true\"></i></a></li>");
document.write("                            <li> <a href=\"http:\/\/noise-planet.org\/en\/project.html\" class=\"smoothScroll\">Project</a></li>");
document.write("                            <li> <a href=\"http:\/\/noise-planet.org\/en\/onomap.html\" class=\"smoothScroll\">OnoMap</a></li>");
document.write("							<li> <a href=\"http:\/\/noise-planet.org\/en\/noisecapture.html\" class=\"smoothScroll\">NoiseCapture</a></li>");
document.write("                            <li> <a href=\"http:\/\/noise-planet.org\/en\/noisemodelling.html\" class=\"smoothScroll\">NoiseModelling</a></li>");
document.write("                            <li> <a href=\"http:\/\/noise-planet.org\/en\/leaflet_noisecapture\/index.html\" class=\"smoothScroll\">Map</a></li>");
document.write("                            <li> <a href=\"http:\/\/data.noise-planet.org\/en\/index.html\" class=\"smoothScroll\">Data</a></li>");
document.write("                            <li> <a href=\"http:\/\/noise-planet.org\/en\/publication.html\" class=\"smoothScroll\">Publications</a></li>");
document.write("                            <li> <a href=\"http:\/\/noise-planet.org\/en\/contact.html\" class=\"smoothScroll\">Contact</a></li>");     
document.write("                    </div><!--/nav-collapse -->");
document.write("                </div><!--/container -->");
document.write("            </div><!--/navbar navbar-inverse navbar-fixed-top -->");
document.write("        </div><!--/navbar-main -->");