document.write( '<!-- This file contains the footer and the credits for the Noise-Planet website -->\n' );
document.write( '\n' );
document.write( '\n' );
document.write( '    <div id=\"footerwrap\">\n' );
document.write( '        <div class=\"container centered\">\n' );
document.write( '            <h4><a data-toggle=\"modal\" href=\"#credits\">Credits</a> | <img src=\"./assets/img/logos/twitter.png\" height=\"25px\" width=\"25px\"  alt=\"Twitter\"><a href=\"https://twitter.com/Noise_Planet\" target=\"blank\"> @Noise_Planet</a></h4>\n' );
document.write( '        </div>\n' );
document.write( '\n' );
document.write( '        <div class=\"modal fade\" id=\"credits\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"myModalLabel\" aria-hidden=\"true\">\n' );
document.write( '            <div class=\"modal-dialog\">\n' );
document.write( '                <div class=\"modal-content\">\n' );
document.write( '                    <div class=\"modal-header\">\n' );
document.write( '                        <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-hidden=\"true\">×</button>\n' );
document.write( '                        <h4 class=\"modal-title\">CREDITS</h4>\n' );
document.write( '                    </div>\n' );
document.write( '                    <div class=\"modal-body\">\n' );
document.write( '\n' );
document.write( '                       <h3>Authors</h3>\n' );
document.write( '\n' );
document.write( '                        <p>\n' );
document.write( '                            This website has been developed by the <a href=\"http://www.labsticc.fr/en/teams/m-570-decide.htm\" target=\"blank\">DECIDE</a> team (Lab-STICC - CNRS UMR 6285) and the <a href=\"http://www.umrae.fr/\" target=\"blank\">UMRAE</a> Laboratory (IFSTTAR)</a>.\n' );
document.write( '                        </p>\n' );
document.write( '                    <div class=\"row\">\n' );
document.write( '\n' );
document.write( '                        <div class=\"col-lg-3 col-sm-3 text-center mb-4\">\n' );
document.write( '                          <a href=\"https://www.labsticc.fr\" target=\"blank\"><img class=\"rounded-circle img-fluid d-block mx-auto\" src=\"./assets/img/contact/labsticc.png\" height=\"60px\" alt=\"Lab-STICC\"></a>\n' );
document.write( '                        </div>\n' );
document.write( '                        <div class=\"col-lg-3 col-sm-3 text-center mb-4\">\n' );
document.write( '                          <a href=\"http://www.cnrs.fr\" target=\"blank\"><img class=\"rounded-circle img-fluid d-block mx-auto\" src=\"./assets/img/contact/cnrs.png\" height=\"60px\" alt=\"CNRS\"></a>\n' );
document.write( '                        </div>\n' );
document.write( '                                                <div class=\"col-lg-3 col-sm-3 text-center mb-4\">\n' );
document.write( '                          <a href=\"http://www.umrae.fr/\" target=\"blank\"><img class=\"rounded-circle img-fluid d-block mx-auto\" src=\"./assets/img/contact/umrae.png\" height=\"60px\" alt=\"UMRAE\"></a>\n' );
document.write( '                        </div>\n' );
document.write( '                                                <div class=\"col-lg-3 col-sm-3 text-center mb-4\">\n' );
document.write( '                          <a href=\"http://www.ifsttar.fr\" target=\"blank\"><img class=\"rounded-circle img-fluid d-block mx-auto\" src=\"./assets/img/contact/ifsttar.png\" height=\"60px\" alt=\"Ifsttar\"></a>\n' );
document.write( '                        </div>\n' );
document.write( '                    </div>\n' );
document.write( '\n' );
document.write( '                        <h3>Developments fundings</h3>\n' );
document.write( '\n' );
document.write( '                        <p>\n' );
document.write( '                            <b>NoiseCapture</b> app has been developed thanks to the european <a href=\"https://www.energic-od.eu/\" target=\"blank\">ENERGIC-OD</a> research project and the <a href=\"http://www.geopal.org/accueil\" target=\"blank\">GeoPAL</a> program.\n' );
document.write( '                            <br>\n' );
document.write( '                            <b>NoiseModelling</b> plugin has been developed thanks to the <a href=\"http://www.agence-nationale-recherche.fr/projet-anr/?tx_lwmsuivibilan_pi2%5BCODE%5D=ANR-08-VILL-0005\" target=\"blank\">Eval-PDU</a> and <a href=\"http://onerc.developpement-durable.gouv.fr/fr/projet/vegdud-role-du-vegetal-dans-le-developpement-urbain-durable-une-approche-par-les-enjeux-lies-\" target=\"blank\">VegDUD</a> research projects supported by the French National Research Agency (ANR).\n' );
document.write( '                        </p>                        \n' );
document.write( '\n' );
document.write( '                        <h3>Website theme</h3>\n' );
document.write( '\n' );
document.write( '                        <p>\n' );
document.write( '                            Theme Boostrap 3 based on <a href=\"http://www.blacktie.co/demo/shield/\">Shield</a>, created by <a href=\"http://www.blacktie.co/\">BlackTie.co</a>\n' );
document.write( '                        </p>\n' );
document.write( '\n' );
document.write( '\n' );
document.write( '                        <h3>Other credits</h3>\n' );
document.write( '\n' );
document.write( '                        <a rel=\"license\" href=\"http://creativecommons.org/licenses/by-nc-sa/4.0/\"><img alt=\"Creative Commons License\" style=\"border-width:0\" src=\"https://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png\" /></a><br />All other documents and ressources are produced by DECIDE team (Lab-STICC) & UMRAE team (IFSTTAR) and are credited under a <a rel=\"license\" href=\"http://creativecommons.org/licenses/by-nc-sa/4.0/\">Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License</a>\n' );
document.write( '                    </div>\n' );
document.write( '                    <div class=\"modal-footer\">\n' );
document.write( '                        <button type=\"button\" class=\"btn btn-default\" data-dismiss=\"modal\">Close</button>\n' );
document.write( '                    </div>\n' );
document.write( '                </div><!-- /.modal-content -->\n' );
document.write( '            </div><!-- /.modal-dialog -->\n' );
document.write( '        </div><!-- /.modal -->\n' );
document.write( '    </div>\n' );
document.write( '      \n' );
