document.write("       <div id=\"navbar-main\">");
document.write("            <!-- Fixed navbar -->");
document.write("		<div class=\"navbar navbar-inverse navbar-fixed-top\">");
document.write("                <div class=\"container\">");
document.write("                    <div class=\"navbar-header\">");
document.write("                        <button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\" data-target=\".navbar-collapse\">");
document.write("                            <span class=\"icon icon-bar\" style=\"font-size:30px; color:#3498db;\"></span>");
document.write("                            <span class=\"icon icon-bar\" style=\"font-size:30px; color:#3498db;\"></span>");
document.write("                            <span class=\"icon icon-bar\" style=\"font-size:30px; color:#3498db;\"></span>");
document.write("                        </button>");
document.write("                        <!--<a class=\"navbar-brand hidden-xs hidden-sm\" href=\"#home\"><span style=\"font-size:18px; color:#3498db;\"></span></a>-->");
document.write("                    </div>");
document.write("                    <div class=\"navbar-collapse collapse\">");
document.write("                        <ul class=\"nav navbar-nav\">");
document.write("                            <li> <a href=\"./index.html\" class=\"smoothScroll\"><i class=\"fa fa-home\" aria-hidden=\"true\"></i> Home</a></li>");
document.write("                            <li class=\"dropdown\"><a class=\"dropdown-toggle\" data-toggle=\"dropdown\" href=\"#\">Project <span class=\"caret\"></span></a>");
document.write("                            <ul class=\"dropdown-menu\">");
document.write("                            		  <li><a href=\"./project.html\">Presentation</a></li>");
document.write("                            		  <li><a href=\"./organisation.html\">Organisation</a></li>");
document.write("                            		  <li><a href=\"./how.html\">How it works</a></li>");
document.write("                                      <li><a href=\"./members.html\">Members</a></li>");
document.write("                                      <li><a href=\"./history.html\">History</a></li>");
document.write("                                      <li><a href=\"./publication.html\">Publications</a></li>");
document.write("                                      <li><a href=\"./media.html\">Press center</a></li>");
document.write("                                      <li><a href=\"./resources.html\">Resources</a></li>");
document.write("                            </ul>");				
document.write("                            <li> <a href=\"./onomap.html\" class=\"smoothScroll\">OnoMap</a></li>");
document.write("                            <li class=\"dropdown\"><a class=\"dropdown-toggle\" data-toggle=\"dropdown\" href=\"#\">NoiseCapture<span class=\"caret\"></span></a>");
document.write("                            <ul class=\"dropdown-menu\">");
document.write("                            		  <li><a href=\"./noisecapture.html\">NoiseCapture App</a></li>");
document.write("                                      <li><a href=\"./noisecapture_protocol.html\">Protocol</a></li>");
document.write("                                      <li><a href=\"./noisecapture_calibration.html\">Calibration</a></li>");
document.write("                                      <li><a href=\"./noisecapture_party.html\">NoiseCapture Party</a></li>");
document.write("                                      <li><a href=\"./noisecapture_ambassador.html\">Ambassador</a></li>");
document.write("                                      <li><a href=\"./noisecapture_exploit_data.html\">Exploit data</a></li>");
document.write("                                      <li><a href=\"./NoiseCapture_privacy_policy_history.html\">Privacy Policy</a></li>");
document.write("                                      <li><a href=\"./faq_NoiseCapture.html\">FAQ</a></li>");
document.write("                            </ul>");
document.write("                            <li class=\"dropdown\"><a class=\"dropdown-toggle\" data-toggle=\"dropdown\" href=\"#\">NoiseModelling<span class=\"caret\"></span></a>");
document.write("                            <ul class=\"dropdown-menu\">");
document.write("                            <li> <a href=\"./noisemodelling.html\" class=\"smoothScroll\">NoiseModelling</a></li>");
document.write("                            <li> <a href=\"./noisemodelling_days.html\" class=\"smoothScroll\">NoiseModelling days</a></li>");
document.write("                            </ul>");
document.write("                            <li> <a href=\"./map.html\" class=\"smoothScroll\"><i class=\"fa fa-map\" aria-hidden=\"true\"></i> Map</a></li>");
document.write("                            <li> <a href=\"http://data.noise-planet.org\/index.html\" class=\"smoothScroll\"><i class=\"fa fa-download\" aria-hidden=\"true\"></i> Data</a></li>");
document.write("                            <li> <a href=\"./support.html\" class=\"smoothScroll\"><i class=\"fa fa-rocket\" aria-hidden=\"true\"></i> Support</a></li>");
document.write("                            <li> <a href=\"./contact.html\" class=\"smoothScroll\"><i class=\"fa fa-envelope-o\" aria-hidden=\"true\"></i> Contact</a></li>");
document.write("                         </ul>");
document.write("                    </div><!--/nav-collapse -->");
document.write("                </div><!--/container -->");
document.write("            </div><!--/navbar navbar-inverse navbar-fixed-top -->");
document.write("        </div><!--/navbar-main -->");