document.write("<!-- This file contains the footer and the credits for the Noise-Planet website -->");
document.write("");
document.write("");
document.write("    <div id=\"footerwrap\">");
document.write("        <div class=\"container centered\">");
document.write("            <h4><a data-toggle=\"modal\" href=\"#credits\">Credits<\/a> | <img src=\"..\/assets\/img\/logos\/twitter.png\" height=\"25px\" width=\"25px\"  alt=\"Twitter\"><a href=\"https:\/\/twitter.com\/Noise_Planet\" target=\"blank\"> @Noise_Planet<\/a><\/h4>");
document.write("        <\/div>");
document.write("");
document.write("        <div class=\"modal fade\" id=\"credits\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"myModalLabel\" aria-hidden=\"true\">");
document.write("            <div class=\"modal-dialog\">");
document.write("                <div class=\"modal-content\">");
document.write("                    <div class=\"modal-header\">");
document.write("                        <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-hidden=\"true\">&times;<\/button>");
document.write("                        <h4 class=\"modal-title\">CREDITS<\/h4>");
document.write("                    <\/div>");
document.write("                    <div class=\"modal-body\">");
document.write("");
document.write("                       <h3>Authors<\/h3>");
document.write("");
document.write("                        <p>");
document.write("                            This website has been developed by the <a href=\"http:\/\/www.labsticc.fr\/en\/teams\/m-570-decide.htm\" target=\"blank\">DECIDE team<\/a> (Lab-STICC) and the <a href=\"http:\/\/www.lae.ifsttar.fr\/\" target=\"blank\">LAE Laboratory<\/a> (IFSTTAR)<\/a>");
document.write("                        <\/p>                    ");
document.write("");
document.write("                        <h3>Developments fundings<\/h3>");
document.write("");
document.write("                        <p>");
document.write("                            <b>NoiseCapture<\/b> app has been developed thanks to the european <a href=\"http:\/\/www.energic-od.eu\/\" target=\"blank\">ENERGIC-OD<\/a> research project and the <a href=\"http:\/\/www.geopal.org\/accueil\" target=\"blank\">GeoPAL<\/a> program.");
document.write("                            <br>");
document.write("                            <b>NoiseModelling<\/b> plugin has been developed thanks to the <a href=\"http:\/\/www.agence-nationale-recherche.fr\/projet-anr\/?tx_lwmsuivibilan_pi2%5BCODE%5D=ANR-08-VILL-0005\" target=\"blank\">Eval-PDU<\/a> and <a href=\"http:\/\/onerc.developpement-durable.gouv.fr\/fr\/projet\/vegdud-role-du-vegetal-dans-le-developpement-urbain-durable-une-approche-par-les-enjeux-lies-\" target=\"blank\">VegDUD<\/a> research projects supported by the French National Research Agency (ANR).");
document.write("                        <\/p>                        ");
document.write("");
document.write("                        <h3>Website theme<\/h3>");
document.write("");
document.write("                        <p>");
document.write("                            Theme Boostrap 3 based on <a href=\"http:\/\/www.blacktie.co\/demo\/shield\/\">Shield<\/a>, created by <a href=\"http:\/\/www.blacktie.co\/\">BlackTie.co<\/a>");
document.write("                        <\/p>");
document.write("");
document.write("");
document.write("                        <h3>Other credits<\/h3>");
document.write("");
document.write("                        <a rel=\"license\" href=\"http:\/\/creativecommons.org\/licenses\/by-nc-sa\/4.0\/\"><img alt=\"Creative Commons License\" style=\"border-width:0\" src=\"https:\/\/i.creativecommons.org\/l\/by-nc-sa\/4.0\/88x31.png\" \/><\/a><br \/>All other documents and ressources are produced by DECIDE team (Lab-STICC) & LAE (IFSTTAR) and are credited under a <a rel=\"license\" href=\"http:\/\/creativecommons.org\/licenses\/by-nc-sa\/4.0\/\">Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License<\/a>");
document.write("                    <\/div>");
document.write("                    <div class=\"modal-footer\">");
document.write("                        <button type=\"button\" class=\"btn btn-default\" data-dismiss=\"modal\">Close<\/button>");
document.write("                    <\/div>");
document.write("                <\/div><!-- \/.modal-content -->");
document.write("            <\/div><!-- \/.modal-dialog -->");
document.write("        <\/div><!-- \/.modal -->");
document.write("    <\/div>");
document.write("      ");

