document.write("<!-- Ce fichier contient le footer et les crédits pour le site web Noise-Planet -->");
document.write("");
document.write("    <div id=\"footerwrap\">");
document.write("        <div class=\"container centered\">");
document.write("            <h4><a data-toggle=\"modal\" href=\"#credits\">Crédits<\/a> | <img src=\"..\/..\/assets\/img\/logos\/twitter.png\" height=\"25px\" width=\"25px\"  alt=\"Twitter\"><a href=\"https:\/\/twitter.com\/Noise_Planet\" target=\"blank\"> @Noise_Planet<\/a><\/h4>");
document.write("        <\/div>");
document.write("");
document.write("        <div class=\"modal fade\" id=\"credits\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"myModalLabel\" aria-hidden=\"true\">");
document.write("            <div class=\"modal-dialog\">");
document.write("                <div class=\"modal-content\">");
document.write("                    <div class=\"modal-header\">");
document.write("                        <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-hidden=\"true\">&times;<\/button>");
document.write("                        <h4 class=\"modal-title\">CRÉDITS<\/h4>");
document.write("                    <\/div>");
document.write("                    <div class=\"modal-body\">");
document.write("");
document.write("                       <h3>Auteurs<\/h3>");
document.write("");
document.write("                        <p>");
document.write("                            Ce site internet a été développé par l'équipe <a href=\"http:\/\/www.labsticc.fr\/en\/teams\/m-570-decide.htm\" target=\"blank\">DECIDE<\/a> (Lab-STICC) et par le <a href=\"http:\/\/www.lae.ifsttar.fr\/\" target=\"blank\">LAE Laboratory<\/a> (IFSTTAR)<\/a>");
document.write("                        <\/p>                    ");
document.write("");
document.write("                        <h3>Financeurs<\/h3>");
document.write("");
document.write("                        <p>");
document.write("                            L'application <b>NoiseCapture<\/b> a été développée avec le soutien du projet de recherche européen <a href=\"http:\/\/www.energic-od.eu\/\" target=\"blank\">ENERGIC-OD<\/a> et du programme <a href=\"http:\/\/www.geopal.org\/accueil\" target=\"blank\">GeoPAL<\/a>.");
document.write("                            <br>");
document.write("                            Le plugin <b>NoiseModelling<\/b> a été développé avec le soutien des projets de recherche <a href=\"http:\/\/www.agence-nationale-recherche.fr\/projet-anr\/?tx_lwmsuivibilan_pi2%5BCODE%5D=ANR-08-VILL-0005\" target=\"blank\">Eval-PDU<\/a> et <a href=\"http:\/\/onerc.developpement-durable.gouv.fr\/fr\/projet\/vegdud-role-du-vegetal-dans-le-developpement-urbain-durable-une-approche-par-les-enjeux-lies-\" target=\"blank\">VegDUD<\/a>, via l'Agence Nationale de la Recherche (ANR).");
document.write("                        <\/p>                        ");
document.write("");
document.write("                        <h3>Thème du site web<\/h3>");
document.write("");
document.write("                        <p>");
document.write("                            Thème Boostrap 3 basé sur <a href=\"http:\/\/www.blacktie.co\/demo\/shield\/\">Shield<\/a>, créé par <a href=\"http:\/\/www.blacktie.co\/\">BlackTie.co<\/a>");
document.write("                        <\/p>");
document.write("");
document.write("                        <h3>Autres crédits<\/h3>");
document.write("");
document.write("                        <a rel=\"license\" href=\"http:\/\/creativecommons.org\/licenses\/by-nc-sa\/4.0\/\"><img alt=\"Creative Commons License\" style=\"border-width:0\" src=\"https:\/\/i.creativecommons.org\/l\/by-nc-sa\/4.0\/88x31.png\" \/><\/a><br \/>Tous les autres documents ou ressources ont été créés par les équipes DECIDE (Lab-STICC) & LAE (IFSTTAR) et sont crédités sous la licence \"<a rel=\"license\" href=\"http:\/\/creativecommons.org\/licenses\/by-nc-sa\/4.0\/\">Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License<\/a>\"");
document.write("                    <\/div>");
document.write("                    <div class=\"modal-footer\">");
document.write("                        <button type=\"button\" class=\"btn btn-default\" data-dismiss=\"modal\">Close<\/button>");
document.write("                    <\/div>");
document.write("                <\/div><!-- \/.modal-content -->");
document.write("            <\/div><!-- \/.modal-dialog -->");
document.write("        <\/div><!-- \/.modal -->");
document.write("    <\/div>");

